# Generated by Django 3.1 on 2021-03-29 14:27

from django.db import migrations, models
import registerapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, validators=[registerapp.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='passward',
            field=models.CharField(max_length=20, validators=[registerapp.models.validate_passward]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(validators=[registerapp.models.validate_phone]),
        ),
    ]
